config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'diaries#index'
  resources :users, only: :show
  resources :diaries, except: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
class Diary < ApplicationRecord
  validates :diary_date, presence: true
  validates :title, presence: true, length: { in: 0..14 }
  validates :images, content_type: [:png, :jpg, :jpeg], length: {maximum: 3, message: "は3つまでです"}
  
  belongs_to :user

  has_many_attached :images, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 10 }
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: 'は半角英数字混合で入力してください' }

  has_many :diaries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :move_to_index, only: [:edit, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :today_data


  def index
    if user_signed_in?
      @diary_count = Diary.where(user_id: current_user.id).where(diary_date: Date.today).count
      @diaries = current_user.diaries.includes(:user)
    end
  end


  def show
    @diary = Diary.find(params[:id])
  end


  def new
    @diary = Diary.new
  end


  def create
    @diary = Diary.new(diary_params)
    if user_signed_in?
      @diary_count = Diary.where(user_id: current_user.id).where(diary_date: Date.today).count
    end
    if @diary.valid?
      if @diary_count < 1
        @diary.save
        flash[:notice] = "記録完了！"
        redirect_to user_path(current_user)
      else
        flash.now[:notice] = "※日記は1日1つまで"
        render :new
      end
    else
      render :new
    end
  end


  def edit
    @diary = Diary.find(params[:id])
  end


  def update
    @diary = Diary.find(params[:id])
    if @diary.update(diary_params)
      redirect_to diary_path(@diary)
      flash[:notice] = "編集完了！"
    else
      render :edit
    end
  end


  def destroy
    @diary = Diary.find(params[:id])
    @diary.destroy
    redirect_to user_path(current_user)
  end


  private
  def diary_params
    params.require(:diary).permit(:diary_date, :title, :text, images:[]).merge(user_id: current_user.id)
  end

  def move_to_index
    @diary = Diary.find(params[:id])
    if user_signed_in? && (current_user.id != @diary.user_id)
      redirect_to action: :index
    end
  end

  def today_data
    @diaries = Diary.includes(:user)
    @datas = []
    @diaries.each do |diary|
      diary_jst = diary[:diary_date].in_time_zone('Tokyo')
      if (diary_jst.to_s.match(/#{Date.today.to_s}.+/)) 
        @datas << diary
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :today_data

  def show
    if user_signed_in?
      @diary_count = Diary.where(user_id: current_user.id).where(diary_date: Date.today).count
    end
    @user = User.find(params[:id])
    @diaries = @user.diaries.includes(:user)
  end

  
  private
  def today_data
    @diaries = Diary.includes(:user)
    @datas = []
    @diaries.each do |diary|
      diary_jst = diary[:diary_date].in_time_zone('Tokyo')
      if (diary_jst.to_s.match(/#{Date.today.to_s}.+/)) 
        @datas << diary
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/diaries/edit.html.erb
<div class="wrapper">


  <div class="sub-wrapper">
    <div class="side-bar">
      <%= render "shared/side_bar" %>
    </div>

    <div class="main-bar">
      <div class="error-bar">
          <% if flash[:notice] %>
          <p><%= flash[:notice] %></p>
          <% end %>
      </div>
      
      <%= form_with model: @diary, url: diary_path, id: "new_edit", local: true do |f| %>

        <%= render 'shared/error_messages', model: f.object %>

        <div class="form-group">
          <div class="forms">
            <div class="form">
              <div class="form-title">･ー Date ー･</div>
              <div class="diary-date-form"><%= f.date_select :diary_date %></div>
            </div>

            <div class="contents-form">
              <div class="form-left">
                <div class="form">
                  <div class="form-title">･ー Title ー･</div>
                  <div class="diary-title-form"><%= f.text_field :title %></div>
                </div>

                <div class="form">
                  <div class="form-title">･ー Text ー･</div>
                  <div class="diary-text-form"><%= f.text_area :text %></div>
                </div>
              </div>

              <div class="form-right">
                <div class="form">
                  <div class="form-title">･ー Image ー･</div>
                  <div class="click-upload">
                    <%= f.file_field :images, accept: ".png, .jpg, .jpeg", name: 'diary[images][]', data: {index: 0} %>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="submit">
            <%= f.submit %>
          </div>
        </div>

      <% end %>
    </div>
  </div>

</div>

app/views/diaries/index.html.erb
<div class="wrapper">

  <div class="sub-wrapper">
    <div class="side-bar">
      <%= render "shared/side_bar" %>
    </div>

    <div class="main-bar">
      <div class="error-bar">
          <% if flash[:notice] %>
          <p><%= flash[:notice] %></p>
          <% end %>
      </div>

      <% if user_signed_in? %>
        <div class="main-icon">
          <% if @diary_count<1 %>
            <%= link_to new_diary_path, class:"link" do %>
              <%= image_tag 'icon_pen.png' , size: '80x80' %>
              <div class="icon-message">今日の日記を書く</div>
            <% end %>
          <% end %>
        </div>

        <div class="main-title">
          MyPage
        </div>

        <div class="calendar">
          <%= month_calendar attribute: :diary_date, events: @diaries do |date, diaries| %>
            <%= date.day %>

            <% diaries.each do |diary| %>
              <div class="diary-title">
                <%= link_to diary.title, diary_path(diary), class:"link" %>
              </div>
            <% end %>
          <% end %>
        </div>

      <% end %>
    </div>
  </div>

</div>

app/views/diaries/new.html.erb
<div class="wrapper">
  <div class="sub-wrapper">
    <div class="side-bar">
      <%= render "shared/side_bar" %>
    </div>

    <div class="main-bar">
      <div class="error-bar">
          <% if flash[:notice] %>
          <p><%= flash[:notice] %></p>
          <% end %>
      </div>

      <%= form_with model: @diary, url: diaries_path, id: "new_edit", local: true do |f| %>

        <%= render 'shared/error_messages', model: f.object %>

        <div class="form-group">
          <div class="forms">
            <div class="form">
              <div class="form-title">･ー Date ー･</div>
              <div class="diary-date-form"><%= f.date_select :diary_date %></div>
            </div>

            <div class="contents-form">
              <div class="form-left">
                <div class="form">
                  <div class="form-title">･ー Title ー･</div>
                  <div class="diary-title-form"><%= f.text_field :title %></div>
                </div>

                <div class="form">
                  <div class="form-title">･ー Text ー･</div>
                  <div class="diary-text-form"><%= f.text_area :text %></div>
                </div>
              </div>

              <div class="form-right">
                <div class="form">
                  <div class="form-title">･ー Image ー･</div>
                  <div class="click-upload">
                    <%= f.file_field :images, accept: ".png, .jpg, .jpeg", name: 'diary[images][]', data: {index: 0} %>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="submit">
            <%= f.submit %>
          </div>
        </div>

      <% end %>
    </div>
  </div>

</div>

app/views/diaries/show.html.erb
<div class="wrapper">


  <div class="sub-wrapper">
    <div class="side-bar">
      <%= render "shared/side_bar" %>
    </div>

    <div class="main-bar">
      <div class="error-bar">
          <% if flash[:notice] %>
          <p><%= flash[:notice] %></p>
          <% end %>
      </div>
      
      <div class="show-contents">
        <div class="buttons">
          <% if user_signed_in? && (current_user.id == @diary.user_id) %>
            <%= link_to 'Edit', edit_diary_path(@diary), class: "link" %>
            <%= link_to 'Delete', diary_path(@diary), method: :delete, class: "link"  %>
          <% end %>
        </div>

        <div class="show-date">
          ･ー <%= @diary.diary_date.year %>/<%= @diary.diary_date.month %>/<%= @diary.diary_date.day %> ー･
        </div>

        <div class="show-body">
          <div class="show-body-left">
            <div class="show-content upper">
              <span class="content-title">Title:</span>
              <span class="title-field"><%= @diary.title %></span>
            </div>

            <div class="show-content lower">
              <div class="content-title">Text:</div>
              <div class="text-field">
                <% if @diary.text.present? %>
                  <%= @diary.text %>
                <% else %>
                  <div class="no-attached">本文はありません</div>
                <% end %>
              </div>
            </div>
          </div>

          <div class="show-body-right">
            <div class="show-content right">
              <div class="content-title">Image:</div>
              <% if @diary.images.attached? %>
                <div class="slider">
                  <% @diary.images.each do |image| %>
                    <%= image_tag image %>
                  <% end %>
                </div>
              <% else %>
                <div class="no-attached">画像はありません</div>
              <% end %>
            </div>
          </div>
        </div>

      </div>

    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RealMeDiary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Caveat">
    
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

  </head>

  <body>
    <%= render "shared/header" %>
    <%= yield %>

  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'>※<%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<div class="header-wrapper">

  <div class="header-lists">

    <div class="left-header">
      <%= image_tag 'real-me-diary_logo.png', size: '400x80' %>
    </div>

    <div class="right-header">
      <% if user_signed_in? %>
        <li class="right-list1">こんにちは、<span class="login-name"><%= current_user.name %></span>さん</li>
        <div class="right-list2-group">
          <li class="right-list2"><%= link_to 'MyPage', user_path(current_user), class:"link" %></li>
          <li class="right-list2"><%= link_to 'Logout', destroy_user_session_path, method: :delete, class:"link" %></li>
        </div>
      <% else %>
        <div class="right-list2-group">
          <li class="right-list2"><%= link_to 'Login', new_user_session_path, class:"link" %></li>
          <li class="right-list2"><%= link_to 'SignUp', new_user_registration_path, class:"link" %></li>
        </div>
      <% end %>
    </div>

  </div>

</div>

app/views/shared/_side_bar.html.erb
<div class="side-wrapper">
  <div class="side-title">
    Today's Diaries
  </div>

  <div class="side-date">
    <%= Date.today.year %>/<%= Date.today.month %>/<%= Date.today.day %>
  </div>

  <% @datas.each do |data| %>
    <div class="today-data">
      <%= link_to data.user.name, user_path(data.user), class:"link1" %>
      <span>:</span>
      <%= link_to data.title, diary_path(data), class:"link2" %>
    </div>
  <% end %>
</div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '←'), calendar.url_for_previous_view, class:"link" %>
      <span class="calendar-title1"><%= start_date.month %></span>
      <span class="calendar-title2"><%= t('date.month_names')[start_date.month] %></span>
    <%= link_to t('simple_calendar.next', default: '→'), calendar.url_for_next_view, class:"link" %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th class="day-name"><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr class="calendar-day">
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<div class="wrapper">


  <div class="sub-wrapper">
    <div class="side-bar">
      <%= render "shared/side_bar" %>
    </div>

    <div class="main-bar">
      <div class="error-bar">
          <% if flash[:notice] %>
          <p><%= flash[:notice] %></p>
          <% end %>
      </div>

      <div class="main-icon">
        <% if user_signed_in? && (current_user.id == @user.id) && @diary_count<1 %>
          <%= link_to new_diary_path, class:"link" do %>
            <%= image_tag 'icon_pen.png' , size: '80x80' %>
            <div class="icon-message">今日の日記を書く</div>
          <% end %>
        <% end %>
      </div>

      <div class="main-title">
        <% if user_signed_in? && (current_user.id == @user.id) %>
          MyPage
        <% else %>
          <span class="user-name"><%= @user.name %></span>'s Diary
        <% end %>
      </div>

      <div class="calendar">
        <%= month_calendar attribute: :diary_date, events: @diaries do |date, diaries| %>
          <%= date.day %>

          <% diaries.each do |diary| %>
            <div class="diary-title">
              <%= link_to diary.title, diary_path(diary), class:"link" %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

</div>